### PR TITLE
Feature/lupe/add pixel by pixel comparison strategy

### PR DESCRIPTION
**Pull request by lukasz-pekala**

### CODE REVIEW

**Comment by cezarypiatek** [comment]
@lukasz-pekala can you provide a sample use case when the new image comparison strategy is applicable? What are the advantages over the existing strategy?

**Comment by lukasz-pekala** [comment]
> @lukasz-pekala can you provide a sample use case when the new image comparison strategy is applicable? What are the advantages over the existing strategy?

@cezarypiatek 

We have numerous cases when it seems that the browser (Chrome in our case) sometimes renders elements a little bit differently even though no css styles were changed for these elements and no browser update.
The issue occurs often on round elements or elements with rounded corners (sometimes even on input fields with round corners). It seems that there are just a few pixels of difference that make entire matching of screenshot to the pattern to fail.
We want to mitigate that by setting a small threshold
image
Blurred shadows can also pose an issue:
image

**Comment by lukasz-pekala** [comment]
This PR is subject to change. I'll let you know @cezarypiatek when it's ready to review

**Comment by lukasz-pekala** [comment]
> This PR is subject to change. I'll let you know @cezarypiatek when it's ready to review

PR is ready to be reviewed.
I've noticed that using this strategy we were able to reduce average time of test suite execution from 26 minutes to 19-20 minutes.
Calculating hash is slower than comparing pixel by pixel.

P.S. I've also noticed that there are similar observations on the internet: https://stackoverflow.com/questions/2031217/what-is-the-fastest-way-i-can-compare-two-equal-size-bitmaps-to-determine-whethe

**Pull request closed without merging**
